### ISSUE TITLE
Allow substitutions to accept dicts, lists, etc.

### ISSUE THREAD

**Issue by mforbes** [executablebooks/MyST-Parser#510]
### Describe the problem/need and solution

In situations where you're trying to use many substitutions, it can be convenient to have namespaces within `myst_substitutions` to prevent name collisions, for better organization.  However, currently, `myst_substitution` values must be `str`, `int`, or `float`.  For example, the following

```python
# conf.py
myst_substitutions = {
    "author": "My name",
    "syllabus": {
        "course_number": 581,
        "instructors": ["Instructor 1", "Instructor 2"],
    }
}
```

fails with warning:

```bash
WARNING: myst configuration invalid: 'substitutions' must be (<class 'str'>, <class 'int'>, <class 'float'>) (got {'course_number': '581'} that is a <class 'dict'>).
```
**Solution**

Allowing for dictionaries would enable users to make namespaces - in this case, I could logically group all of the syllabus information and then use it in the syllabus document with Jijna templates like `{{ syllabus.course_number }}`

Similarly, allowing for lists, etc. would allow one to use constructs like `{{ syllabus.instructors|join(', ') }}`.

**Benefit**
This helps users group substitutions, allows formatting like `{{ '{course_number}'.format(**syllabus) }}` (see https://github.com/executablebooks/MyST-Parser/issues/279#issuecomment-1019948255), and avoid name clashes.  It is also consistent with the [Zen of python](https://www.python.org/dev/peps/pep-0020/).

### Guide for implementation

A simple two-line change in `main.py:MdParserConfig` allows for this:

```python
    substitutions: Dict[str, Union[str, int, float, dict]] = attr.ib(     # <-- Add dict here
        factory=dict,
        validator=deep_mapping(
            instance_of(str), instance_of((str, int, float, dict)), instance_of(dict)   # <-- Add dict here
        ),
        repr=lambda v: str(list(v)),
    )
```

however, one might want to expand this a bit to recursively check that nested dicts also only contain strings, ints, floats, or dicts of similar.  (I don't think `deep_mapping` does this).

Perhaps this change is enough:
1. It keeps backwards compatibility, checking top-level substitutions for these simple types.
2. It allows users flexibility if they need it by using nested namespaces.

### Tasks and updates

- [ ] Discuss to see if this feature might cause any problems.
- [ ] Consider relaxing the requirements of `int`, `str`, and `float`.
  - [ ] Only in nested scopes, or always?
- [ ] Document substitutions a bit better.
- [ ] Consider the change suggested here https://github.com/executablebooks/MyST-Parser/issues/279#issuecomment-1019948255 (maybe another request?  It is simple though.)
- [ ] Implement changes to `main.py` and possibly a more comprehensive `deep_mapping` validator.
